[display]
fullscreen = false
height = 720
vsync = true
width = 1280

[physics]
fixed_timestep = 0.01666666753590107
gravity = [ 0.0, -9.8100004196167, 0.0 ]

[project]
default_map = 'maps/default.map'
engine_version = '1.0.0'
id = '82fdec8d-b7b4-4bf0-ab52-a37e5945526a'
name = 'SandboxGame'
version = '0.1.0'

[rendering]
ray_tracing = true
shadow_quality = 'high'