[display]
fullscreen = false
height = 720
vsync = true
width = 1280

[physics]
fixed_timestep = 0.01666666753590107
gravity = [ 0.0, -9.8100004196167, 0.0 ]

[project]
default_map = 'maps/default.map'
engine_version = '1.0.0'
id = 'b928b4b2-903f-4de2-bcf6-dd8d41020b78'
name = 'SandboxGame'
version = '0.1.0'

[rendering]
ray_tracing = true
shadow_quality = 'high'