[display]
fullscreen = false
height = 720
vsync = true
width = 1280

[physics]
fixed_timestep = 0.01666666753590107
gravity = [ 0.0, -9.8100004196167, 0.0 ]

[project]
default_map = 'maps/default.map'
engine_version = '1.0.0'
id = 'a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d'
name = 'ActionDemo'
version = '0.1.0'

[rendering]
ray_tracing = true
shadow_quality = 'high'